# Generated by Django 2.1 on 2018-08-27 02:35

from django.db import migrations, models
import djongo.models.fields
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('poster_path', models.CharField(max_length=250)),
                ('poster_home_path', models.CharField(max_length=250)),
                ('link_for_download', models.CharField(max_length=250)),
                ('password_for_download', models.CharField(max_length=250)),
                ('sequence_number', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('synopsis', models.CharField(max_length=250)),
                ('trailer_url', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
                ('length', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('age_rating', models.CharField(max_length=250)),
                ('production_company', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('technical_information', models.CharField(max_length=250)),
                ('site', models.CharField(max_length=250)),
                ('facebook', models.CharField(max_length=250)),
                ('twitter', models.CharField(max_length=250)),
                ('instagram', models.CharField(max_length=250)),
                ('youtube', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField()),
                ('slug', models.CharField(max_length=250)),
                ('poster_thumb_path', models.CharField(max_length=250)),
                ('press_kit_path', models.CharField(max_length=250)),
                ('screening', djongo.models.fields.ArrayModelField(model_container=movies.models.Screening)),
            ],
            options={
                'db_table': 'films',
                'managed': False,
            },
        ),
    ]
