# Generated by Django 2.1.1 on 2018-09-09 21:33

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MongoFilm',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('poster_path', models.CharField(max_length=250)),
                ('poster_home_path', models.CharField(max_length=250)),
                ('link_for_download', models.CharField(max_length=250)),
                ('password_for_download', models.CharField(max_length=250)),
                ('sequence_number', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('synopsis', models.CharField(max_length=250)),
                ('trailer_url', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
                ('length', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('age_rating', models.CharField(max_length=250)),
                ('production_company', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('technical_information', models.TextField()),
                ('site', models.CharField(max_length=250)),
                ('facebook', models.CharField(max_length=250)),
                ('twitter', models.CharField(max_length=250)),
                ('instagram', models.CharField(max_length=250)),
                ('youtube', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField()),
                ('slug', models.CharField(max_length=250)),
                ('poster_thumb_path', models.CharField(max_length=250)),
                ('press_kit_path', models.CharField(max_length=250)),
                ('screening', djongo.models.fields.ArrayModelField(model_container=movies.models.MongoScreening)),
            ],
            options={
                'db_table': 'films',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('poster_path', models.CharField(blank=True, max_length=250, null=True)),
                ('poster_home_path', models.CharField(blank=True, max_length=250, null=True)),
                ('link_for_download', models.CharField(blank=True, max_length=250, null=True)),
                ('password_for_download', models.CharField(blank=True, max_length=250, null=True)),
                ('sequence_number', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('trailer_url', models.CharField(blank=True, max_length=250, null=True)),
                ('genre', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.CharField(blank=True, max_length=250, null=True)),
                ('length', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('age_rating', models.CharField(blank=True, max_length=250, null=True)),
                ('production_company', models.CharField(blank=True, max_length=250, null=True)),
                ('director', models.CharField(blank=True, max_length=250, null=True)),
                ('technical_information', models.TextField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=250, null=True)),
                ('facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, max_length=250, null=True)),
                ('createdAt', models.DateTimeField()),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('poster_thumb_path', models.CharField(blank=True, max_length=250, null=True)),
                ('press_kit_path', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('team_member', models.BooleanField(default=True)),
                ('activity', models.CharField(blank=True, max_length=250, null=True)),
                ('activity_theme', models.TextField(blank=True, null=True)),
                ('quorum_expectation', models.CharField(blank=True, max_length=250, null=True)),
                ('comments', models.TextField(blank=True, max_length=250, null=True)),
                ('accept_terms', models.BooleanField()),
                ('place_name', models.CharField(blank=True, max_length=250, null=True)),
                ('cep', models.CharField(blank=True, max_length=250, null=True)),
                ('street', models.CharField(blank=True, max_length=250, null=True)),
                ('number', models.CharField(blank=True, max_length=250, null=True)),
                ('complement', models.CharField(blank=True, max_length=250, null=True)),
                ('zone', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('public_event', models.BooleanField(default=True)),
                ('uf', models.CharField(blank=True, max_length=250, null=True)),
                ('s_country', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=250, null=True)),
                ('draft', models.CharField(blank=True, max_length=15, null=True)),
                ('real_quorum', models.CharField(blank=True, max_length=250, null=True)),
                ('report_description', models.TextField(blank=True, null=True)),
                ('report_image_1', models.CharField(blank=True, max_length=250, null=True)),
                ('report_image_2', models.CharField(blank=True, max_length=250, null=True)),
                ('report_image_3', models.CharField(blank=True, max_length=250, null=True)),
                ('author_1', models.CharField(blank=True, max_length=250, null=True)),
                ('author_2', models.CharField(blank=True, max_length=250, null=True)),
                ('author_3', models.CharField(blank=True, max_length=250, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movies.Film')),
            ],
        ),
    ]
