#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

cd /app

python manage.py migrate auth
python manage.py migrate
python manage.py collectstatic --noinput
python manage.py makemessages -a
#nginx
#uwsgi --ini /uwsgi.ini
python manage.py runserver 0.0.0.0:8000


