# Generated by Django 2.1.1 on 2018-09-16 22:00

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('app', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=10)),
                ('hash', models.CharField(max_length=50)),
            ],
        ),
    ]
